import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import StyledComponentsRegistry from "./registry";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${manrope.className}`}>
        <StyledComponentsRegistry>
          <div style={{ display: "flex", flexDirection: "column", gap: -20 }}>
            <Navbar />
            {children}
          </div>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
